name: event_ticketing
description: Event Ticketing App — Flutter + Laravel API via ngrok
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1

  # Navigation
  go_router: ^13.2.0

  # HTTP client
  dio: ^5.4.3+1

  # UI
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0

  # Secure token storage
  flutter_secure_storage: ^9.0.0

  # Utils
  intl: ^0.19.0
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
